apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-ingress
  namespace: fy
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: www.dev.fy.com
      http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: fy-www-service
               port:
                 number: 80
