apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-ingress
  namespace: findmytube
  annotations:
    {{ if or (eq .Values.env "production") (eq .Values.env "staging") }}
    cert-manager.io/cluster-issuer: findmytube-clusterissuer
    {{ end }}
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
      - www.{{ .Values.host }}
      {{ if or (eq .Values.env "production") (eq .Values.env "staging") }}
      secretName: {{ .Values.env }}-www-findmytube-tls
      {{ end }}
  rules:
    - host: www.{{ .Values.host }}
      http:
       paths:
         - path: /
           pathType: ImplementationSpecific
           backend:
             service:
               name: findmytube-www-service
               port:
                 number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-root-ingress
  namespace: findmytube
  annotations:
    {{ if or (eq .Values.env "production") (eq .Values.env "staging") }}
    cert-manager.io/cluster-issuer: findmytube-clusterissuer
    {{ end }}
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
      - {{ .Values.host }}
      {{ if or (eq .Values.env "production") (eq .Values.env "staging") }}
      secretName: {{ .Values.env }}-www-root-findmytube-tls
      {{ end }}
  rules:
    - host: {{ .Values.host }}
      http:
       paths:
         - path: /
           pathType: ImplementationSpecific
           backend:
             service:
               name: findmytube-www-service
               port:
                 number: 80
