host: "dev.findmytube.io"
namespace: findmytube

api:
  baseUrl: "http://api.{{ .Values.host }}"

elastic:
  masterHost: "elasticsearch-master.findmytube.svc.cluster.local"

redis:
  masterHost: "findmytube-redis-master.findmytube.svc.cluster.local"
  masterPort: 6379
  slaveHost: "findmytube-redis-replicas.findmytube.svc.cluster.local"
  slavePort: 6379
