host: "findmytube.io"
namespace: findmytube
env: production

version:
  api: 9fc50eea747836d8795617332bfd6a9ab7fc5fd6
  www: cb03cc7b7bcde86a04f009d2492ea46169a4e067
  videoWorker: 10048bd8fe580f07c8e15e2c54d6fd67394b0909
  cronChannelProducer: 10048bd8fe580f07c8e15e2c54d6fd67394b0909
  channelWorker: fa39bf522c8031820a26ec657e1c94417472e591
  cronVideoUpdater: 10048bd8fe580f07c8e15e2c54d6fd67394b0909

elastic:
  masterHost: "findmytube-elasticsearch-es-internal-http.findmytube.svc.cluster.local"

redis:
  masterHost: "findmytube-redis-bitnami-master"
  masterPort: 6379
  slaveHost: "findmytube-redis-replicas.findmytube.svc.cluster.local"
  slavePort: 6379

storage:
  storageClassName: "csi-cinder-high-speed"
