apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-storage-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: 10Gi
