apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-channel-producer
spec:
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: findmytube-cron-channel-producer
            image: ghcr.io/slayug/findmytube/cron-channel-producer:{{ .Values.version.cronChannelProducer }}
            imagePullPolicy: IfNotPresent
            env:
              - name: ELASTIC_HOST
                value: {{ .Values.elastic.masterHost }}
              - name: REDIS_HOST
                value: {{ .Values.redis.masterHost }}
              - name: REDIS_PASSWORD
                valueFrom:
                  secretKeyRef:
                      name: findmytube-redis
                      key: redis-password
          imagePullSecrets:
            - name: regcred
          restartPolicy: OnFailure
