apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-channel-producer
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-channel-producer
            image: ghcr.io/slayug/fy/cron-channel-producer:caca1392ff6c2b67db12f92702f4dc820dd63607
            imagePullPolicy: Always
            env:
              - name: ELASTIC_HOST
                value: {{ .Values.elastic.masterHost }}
              - name: REDIS_HOST
                value: {{ .Values.redis.masterHost }}
              - name: REDIS_PASSWORD
                valueFrom:
                  secretKeyRef:
                      name: findmytube-redis
                      key: redis-password
          imagePullSecrets:
            - name: regcred
          restartPolicy: OnFailure
