apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: findmytube-elasticsearch
spec:
  version: 8.12.2
  nodeSets:
    - name: default
      count: 2
      config:
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: {{ .Values.storage.storageClassName }}
      podTemplate:
        spec:
          initContainers:
            - name: configure-sysctl
              securityContext:
                runAsUser: 0
                privileged: true
              image: busybox
              imagePullPolicy: IfNotPresent
              command: [ "sysctl", "-w", "vm.max_map_count=262144" ]
          containers:
            - name: elasticsearch
              env:
              - name: ES_JAVA_OPTS
                value: -Xms2g -Xmx2g
              resources:
                requests:
                  cpu: 2
                  memory: 3Gi
                limits:
                  cpu: 2
                  memory: 3Gi
