apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: findmytube-elasticsearch
spec:
  version: 8.12.2
  nodeSets:
    - name: default
      count: 3
      config:
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 40Gi
          storageClassName: {{ .Values.storage.storageClassName }}
      podTemplate:
        spec:
          initContainers:
            - name: configure-sysctl
              securityContext:
                runAsUser: 0
                privileged: true
              image: busybox
              imagePullPolicy: IfNotPresent
              command: [ "sysctl", "-w", "vm.max_map_count=262144" ]
          containers:
            - name: elasticsearch
              env:
              - name: ES_JAVA_OPTS
                value: -Xms3g -Xmx3g
              - name: xpack.security.enabled
                value: "false"
              - name: READINESS_PROBE_PROTOCOL
                value: http
              resources:
                requests:
                  cpu: 2
                  memory: 4Gi
                limits:
                  cpu: 2
                  memory: 4Gi
