apiVersion: apps/v1
kind: Deployment
metadata:
  name: findmytube-api
  namespace: findmytube
  labels:
    project: findmytube
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      project: findmytube
      app: api
  template:
    metadata:
      labels:
        project: findmytube
        app: api
    spec:
      containers:
        - name: findmytube-api
          image: ghcr.io/slayug/fy/api:269c3555dde1330526da100b57b046125bb07a5d
          imagePullPolicy: Always
          env:
            - name: ELASTIC_HOST
              value: {{ .Values.elastic.masterHost }}
            - name: REDIS_HOST
              value: {{ .Values.redis.masterHost }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: findmytube-redis
                  key: redis-password
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: "100M"
            limits:
              cpu: 200m
              memory: "100M"
      imagePullSecrets:
      - name: regcred
