apiVersion: apps/v1
kind: Deployment
metadata:
  name: fy-api
  namespace: fy
  labels:
    project: fy
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      project: fy
      app: api
  template:
    metadata:
      labels:
        project: fy
        app: api
    spec:
      containers:
        - name: fy-api
          image: ghcr.io/slayug/fy/api:269c3555dde1330526da100b57b046125bb07a5d
          imagePullPolicy: Always
          env:
            - name: ELASTIC_HOST
              value: {{ .Values.elastic.masterHost }}
            - name: REDIS_HOST
              value: {{ .Values.redis.masterHost }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fy-redis
                  key: redis-password
          ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: regcred
