apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: findmytube
  annotations:
    kubernetes.io/ingress.class: nginx
    {{ if or (eq .Values.env "prod") (eq .Values.env "staging") }}
    cert-manager.io/cluster-issuer: findmytube-clusterissuer
    {{ end }}
spec:
  tls:
    - hosts:
      - api.{{ .Values.host }}
      {{ if or (eq .Values.env "prod") (eq .Values.env "staging") }}
      secretName: {{ .Values.env }}-api-findmytube-tls
      {{ end }}
  rules:
    - host: api.{{ .Values.host }}
      http:
       paths:
         - path: /
           pathType: ImplementationSpecific
           backend:
             service:
               name: findmytube-api-service
               port:
                 number: 80
