apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: findmytube
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.{{ .Values.host }}
      http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: findmytube-api-service
               port:
                 number: 80
