apiVersion: apps/v1
kind: Deployment
metadata:
  name: findmytube-api
  namespace: findmytube
  labels:
    project: findmytube
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      project: findmytube
      app: api
  template:
    metadata:
      labels:
        project: findmytube
        app: api
    spec:
      containers:
        - name: findmytube-api
          image: ghcr.io/slayug/findmytube/api:{{ .Values.version.api }}
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: {{ .Values.env }}
            - name: HOST
              value: {{ .Values.host }}
            - name: ELASTIC_HOST
              value: {{ .Values.elastic.masterHost }}
            - name: REDIS_HOST
              value: {{ .Values.redis.masterHost }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: findmytube-redis-bitnami
                  key: redis-password
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 1
              memory: 1G
            limits:
              cpu: 2
              memory: 3G
      imagePullSecrets:
      - name: regcred-ghcr
