apiVersion: apps/v1
kind: Deployment
metadata:
  name: findmytube-video-worker
  namespace: findmytube
  labels:
    project: findmytube
    app: video-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      project: findmytube
      app: video-worker
  template:
    metadata:
      labels:
        project: findmytube
        app: video-worker
    spec:
      containers:
        - name: findmytube-video-worker
          image: ghcr.io/slayug/fy/video-worker:08dece13a2c2507808445c8a5c399d7837466f40
          imagePullPolicy: Always
          env:
            - name: ELASTIC_HOST
              value: {{ .Values.elastic.masterHost }}
            - name: REDIS_HOST
              value: {{ .Values.redis.masterHost }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: findmytube-redis
                    key: redis-password
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
