apiVersion: apps/v1
kind: Deployment
metadata:
  name: fy-video-worker
  namespace: fy
  labels:
    project: fy
    app: video-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      project: fy
      app: video-worker
  template:
    metadata:
      labels:
        project: fy
        app: video-worker
    spec:
      containers:
        - name: fy-video-worker
          image: ghcr.io/slayug/fy/video-worker:latest
          imagePullPolicy: Always
          env:
            - name: ELASTIC_HOST
              value: {{ .Values.elastic.masterHost }}
            - name: REDIS_HOST
              value: {{ .Values.redis.masterHost }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: fy-redis
                    key: redis-password
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
