apiVersion: apps/v1
kind: Deployment
metadata:
  name: findmytube-channel-worker
  namespace: findmytube
  labels:
    project: findmytube
    app: channel-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      project: findmytube
      app: channel-worker
  template:
    metadata:
      labels:
        project: findmytube
        app: channel-worker
    spec:
      containers:
        - name: findmytube-channel-worker
          securityContext:
            allowPrivilegeEscalation: false
          image: ghcr.io/slayug/findmytube/channel-worker:{{ .Values.version.channelWorker }}
          imagePullPolicy: Always
          env:
            - name: ELASTIC_HOST
              value: {{ .Values.elastic.masterHost }}
            - name: REDIS_HOST
              value: {{ .Values.redis.masterHost }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: findmytube-redis-bitnami
                    key: redis-password
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred-ghcr
