apiVersion: apps/v1
kind: Deployment
metadata:
  name: fy-channel-worker
  namespace: fy
  labels:
    project: fy
    app: channel-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      project: fy
      app: channel-worker
  template:
    metadata:
      labels:
        project: fy
        app: channel-worker
    spec:
      containers:
        - name: fy-channel-worker
          image: ghcr.io/slayug/fy/channel-worker:98a5e10ce3925e00fa08c7a8cb47eb99eb144020
          imagePullPolicy: Always
          env:
            - name: ELASTIC_HOST
              value: {{ .Values.elastic.masterHost }}
            - name: REDIS_HOST
              value: {{ .Values.redis.masterHost }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: fy-redis
                    key: redis-password
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
