apiVersion: batch/v1
kind: Job
metadata:
  name: findmytube-producer
  namespace: findmytube
  labels:
    project: findmytube
    app: producer
spec:
  template:
    spec:
      containers:
      - name: findmytube-producer
        image: ghcr.io/slayug/fy/producer:269c3555dde1330526da100b57b046125bb07a5d
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: {{ .Values.redis.masterHost }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
                name: findmytube-redis
                key: redis-password
      restartPolicy: Never
      imagePullSecrets:
       - name: regcred
