apiVersion: batch/v1
kind: Job
metadata:
  name: producer
  app: fy
spec:
  template:
    spec:
      containers:
      - name: fy-producer
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
