apiVersion: batch/v1
kind: Job
metadata:
  name: findmytube-producer
  namespace: findmytube
  labels:
    project: findmytube
    app: producer
spec:
  template:
    spec:
      containers:
      - name: findmytube-producer
        image: ghcr.io/slayug/findmytube/producer:3e6f535c7c14363b192f8521d9a897ce7a366367
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: {{ .Values.redis.masterHost }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
                name: findmytube-redis-bitnami
                key: redis-password
      restartPolicy: Never
      imagePullSecrets:
       - name: regcred-ghcr
