import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import Image from 'next/image'
import React from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div>
            <Link href="/" style={{fontWeight: 'bold', color: 'white'}}>
              <Image alt="findmytube logo" width="40" height="40" src="/icon.png"/>
              <span style={{marginLeft: '5px'}}>FINDMYTUBE</span>
            </Link>
          </div>
          <div>
            {children}
          </div>
        </div>

      </body>
    </html>
  )
}
