name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [ main ]

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['api', 'www', 'video-worker', 'cron-channel-producer', 'channel-worker']

    # steps to perform in job
    steps:
      - name: set lower case owner name
        run: |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Lerna
        run: |
          yarn install
          yarn run bootstrap:prod
          yarn run build

      - name: Build ${{ matrix.package }} image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          file: ./packages/${{ matrix.package }}/Dockerfile
          context: ./packages/${{ matrix.package }}
          tags: ghcr.io/${{ env.REPO_LC }}/${{ matrix.package }}:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            PACKAGE=${{ matrix.package }}